services:
  backend:
    container_name: "visit-backend"
    build:
      context: backend
      dockerfile: Dockerfile.dev
      additional_contexts:
        common: ./
    depends_on:
      postgres:
        condition: service_healthy
      rclone:
        condition: service_healthy
      notifications-api:
        condition: service_started
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    volumes:
      - ./backend/app:/app/app
      - ./backend/migrations:/app/migrations
      - ./backend/alembic.ini:/app/alembic.ini
      - ./backend/scripts:/app/scripts

  frontend:
    container_name: "visit-frontend"
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    env_file:
      - frontend/.env
    profiles: [frontend]
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/scripts:/app/scripts

  postgres:
    image: postgres:17
    container_name: "visit-postgres"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 50
    volumes:
      - ./data/sql:/var/lib/postgresql/data
    ports:
      - 5432:5432

  rclone-create-bucket:
    image: busybox
    command: mkdir -p /data/s3/visit
    volumes:
      - ./data:/data

  rclone:
    image: rclone/rclone
    ports:
      - "9000:9000"
    volumes:
      - ./data/s3:/data
      - ./util/rclone.conf:/config/rclone/rclone.conf
    command: serve s3 local:/data --addr 0.0.0.0:9000 --allow-origin '*'
    depends_on:
      rclone-create-bucket:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "rclone", "ls", "serves3:/"]
      interval: 1s
      timeout: 1s
      retries: 60

  notifications-api:
    container_name: "visit-notifications-api"
    image: eu.gcr.io/vseth-public/notifications-api
    ports:
      - 6781:6781
    environment:
      NOTIFICATIONS_LOGGING_ONLY: true
      NOTIFICATIONS_UNAUTHENTICATED: true
      LOG_LEVEL: trace

  keycloak:
    container_name: "visit-keycloak"
    image: quay.io/keycloak/keycloak:21.1.2
    environment:
      - KEYCLOAK_ADMIN=keycloak
      - KEYCLOAK_ADMIN_PASSWORD=keycloak
      - KC_HTTP_PORT=8181
    command: start-dev --import-realm --log-level=ERROR
    volumes:
      - "./testdata/fake-vseth.json:/opt/keycloak/data/import/test-data.json"
    ports:
      - "8181:8181"
