"""Add KP models

Revision ID: 0003 
Revises: 0002
Create Date: 2026-04-24 23:01:44.205347

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpindustry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpindustry_name'), 'kpindustry', ['name'], unique=True)
    op.create_table('kpeventboothzone',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('booth_size', sa.Float(), nullable=False),
    sa.Column('base_price', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['kpevent.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'color'),
    sa.UniqueConstraint('event_id', 'name')
    )
    op.create_table('kpeventservice',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confirmation_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('max_quantity_per_booking', sa.Integer(), nullable=False),
    sa.Column('max_total_quantity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['kpevent.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'name')
    )
    op.create_table('kpeventbooking',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('booth_zone_id', sa.Uuid(), nullable=False),
    sa.Column('main_contact_id', sa.Uuid(), nullable=False),
    sa.Column('finalized', sa.Boolean(), nullable=False),
    sa.Column('booth_nr', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['booth_zone_id'], ['kpeventboothzone.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['kpevent.id'], ),
    sa.ForeignKeyConstraint(['main_contact_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'booth_zone_id', 'booth_nr'),
    sa.UniqueConstraint('event_id', 'company_id', 'booth_zone_id')
    )
    op.create_table('kpeventboothzoneservicelink',
    sa.Column('booth_zone_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('included_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booth_zone_id'], ['kpeventboothzone.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['kpeventservice.id'], ),
    sa.PrimaryKeyConstraint('booth_zone_id', 'service_id')
    )
    op.create_table('kpeventservicerequirement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('TEXT', 'FILE', 'IMAGE', 'PDF', 'VIDEO', name='kpeventservicerequirementtype'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['kpeventservice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kpbookingcompanydetails',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('profile', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_person', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('places_of_work', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('employees_count', sa.Integer(), nullable=True),
    sa.Column('employees_count_switzerland', sa.Integer(), nullable=True),
    sa.Column('offer_internship', sa.Boolean(), nullable=False),
    sa.Column('offer_part_time', sa.Boolean(), nullable=False),
    sa.Column('offer_thesis', sa.Boolean(), nullable=False),
    sa.Column('languages', postgresql.ARRAY(sa.Enum('ENGLISH', 'GERMAN', 'FRENCH', 'ITALIAN', name='kpcompanylanguage')), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['kpeventbooking.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_table('kpeventbookingservice',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('included_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['kpeventbooking.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['kpeventservice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nametag',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['kpeventbooking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kpbookingcompanydetailsindustrylink',
    sa.Column('booking_company_details_id', sa.Uuid(), nullable=False),
    sa.Column('industry_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['booking_company_details_id'], ['kpbookingcompanydetails.id'], ),
    sa.ForeignKeyConstraint(['industry_id'], ['kpindustry.id'], ),
    sa.PrimaryKeyConstraint('booking_company_details_id', 'industry_id')
    )
    op.drop_table('kpeventcompanylink')
    op.drop_constraint(op.f('companyinvite_company_id_fkey'), 'companyinvite', type_='foreignkey')
    op.create_foreign_key(None, 'companyinvite', 'company', ['company_id'], ['id'])
    op.add_column('kpevent', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('kpevent', sa.Column('finalization_deadline', sa.Date(), nullable=False))
    op.drop_index(op.f('ix_kpevent_year'), table_name='kpevent')
    op.create_index(op.f('ix_kpevent_name'), 'kpevent', ['name'], unique=True)
    op.drop_column('kpevent', 'year')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpevent', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_kpevent_name'), table_name='kpevent')
    op.create_index(op.f('ix_kpevent_year'), 'kpevent', ['year'], unique=True)
    op.drop_column('kpevent', 'finalization_deadline')
    op.drop_column('kpevent', 'name')
    op.drop_constraint(None, 'companyinvite', type_='foreignkey')
    op.create_foreign_key(op.f('companyinvite_company_id_fkey'), 'companyinvite', 'company', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_table('kpeventcompanylink',
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('kpeventcompanylink_company_id_fkey')),
    sa.ForeignKeyConstraint(['event_id'], ['kpevent.id'], name=op.f('kpeventcompanylink_event_id_fkey')),
    sa.PrimaryKeyConstraint('event_id', 'company_id', name=op.f('kpeventcompanylink_pkey'))
    )
    op.drop_table('kpbookingcompanydetailsindustrylink')
    op.drop_table('nametag')
    op.drop_table('kpeventbookingservice')
    op.drop_table('kpbookingcompanydetails')
    op.drop_table('kpeventservicerequirement')
    op.drop_table('kpeventboothzoneservicelink')
    op.drop_table('kpeventbooking')
    op.drop_table('kpeventservice')
    op.drop_table('kpeventboothzone')
    op.drop_index(op.f('ix_kpindustry_name'), table_name='kpindustry')
    op.drop_table('kpindustry')
    # ### end Alembic commands ###
