"""base models

Revision ID: df4bf0a31654
Revises: 0004
Create Date: 2026-04-25 00:08:14.442468

"""

from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: Union[str, Sequence[str], None] = "0004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "company",
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "company",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "companyinvite",
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "companyinvite",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "companyinvite",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.add_column(
        "confirmemailtoken",
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "confirmemailtoken",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "confirmemailtoken",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_confirmemailtoken_id"), table_name="confirmemailtoken")
    op.add_column(
        "forgetpasswordtoken",
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "forgetpasswordtoken",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "forgetpasswordtoken",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_forgetpasswordtoken_id"), table_name="forgetpasswordtoken")
    op.add_column(
        "kpbookingcompanydetails",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "kpbookingcompanydetails",
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "kpbookingcompanydetails",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "kpbookingcompanydetailsindustrylink",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "kpbookingcompanydetailsindustrylink",
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "kpevent",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "kpevent",
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "kpevent",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "kpeventbooking",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "kpeventbooking",
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "kpeventbooking",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.drop_column("kpeventbooking", "deleted")
    op.add_column(
        "kpeventbookingservice",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "kpeventbookingservice",
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "kpeventbookingservice",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "kpeventboothzone",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "kpeventboothzone",
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "kpeventboothzone",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.drop_column("kpeventboothzone", "deleted")
    op.add_column(
        "kpeventboothzoneservicelink",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "kpeventboothzoneservicelink",
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "kpeventservice",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "kpeventservice",
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "kpeventservice",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.drop_column("kpeventservice", "deleted")
    op.add_column(
        "kpeventservicerequirement",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "kpeventservicerequirement",
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "kpeventservicerequirement",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "kpindustry",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "kpindustry",
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "kpindustry",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "nametag",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "nametag",
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "nametag",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "refreshtoken",
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "refreshtoken",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "refreshtoken",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_refreshtoken_id"), table_name="refreshtoken")
    op.add_column(
        "role",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "role",
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "role",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "user",
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "user",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "userrole",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "userrole",
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("userrole", "deleted_at")
    op.drop_column("userrole", "created_at")
    op.drop_column("user", "updated_at")
    op.drop_column("user", "deleted_at")
    op.drop_column("user", "created_at")
    op.drop_column("role", "updated_at")
    op.drop_column("role", "deleted_at")
    op.drop_column("role", "created_at")
    op.create_index(op.f("ix_refreshtoken_id"), "refreshtoken", ["id"], unique=False)
    op.alter_column(
        "refreshtoken",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("refreshtoken", "updated_at")
    op.drop_column("refreshtoken", "deleted_at")
    op.drop_column("nametag", "updated_at")
    op.drop_column("nametag", "deleted_at")
    op.drop_column("nametag", "created_at")
    op.drop_column("kpindustry", "updated_at")
    op.drop_column("kpindustry", "deleted_at")
    op.drop_column("kpindustry", "created_at")
    op.drop_column("kpeventservicerequirement", "updated_at")
    op.drop_column("kpeventservicerequirement", "deleted_at")
    op.drop_column("kpeventservicerequirement", "created_at")
    op.add_column(
        "kpeventservice",
        sa.Column("deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("kpeventservice", "updated_at")
    op.drop_column("kpeventservice", "deleted_at")
    op.drop_column("kpeventservice", "created_at")
    op.drop_column("kpeventboothzoneservicelink", "deleted_at")
    op.drop_column("kpeventboothzoneservicelink", "created_at")
    op.add_column(
        "kpeventboothzone",
        sa.Column("deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("kpeventboothzone", "updated_at")
    op.drop_column("kpeventboothzone", "deleted_at")
    op.drop_column("kpeventboothzone", "created_at")
    op.drop_column("kpeventbookingservice", "updated_at")
    op.drop_column("kpeventbookingservice", "deleted_at")
    op.drop_column("kpeventbookingservice", "created_at")
    op.add_column(
        "kpeventbooking",
        sa.Column("deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("kpeventbooking", "updated_at")
    op.drop_column("kpeventbooking", "deleted_at")
    op.drop_column("kpeventbooking", "created_at")
    op.drop_column("kpevent", "updated_at")
    op.drop_column("kpevent", "deleted_at")
    op.drop_column("kpevent", "created_at")
    op.drop_column("kpbookingcompanydetailsindustrylink", "deleted_at")
    op.drop_column("kpbookingcompanydetailsindustrylink", "created_at")
    op.drop_column("kpbookingcompanydetails", "updated_at")
    op.drop_column("kpbookingcompanydetails", "deleted_at")
    op.drop_column("kpbookingcompanydetails", "created_at")
    op.create_index(
        op.f("ix_forgetpasswordtoken_id"), "forgetpasswordtoken", ["id"], unique=False
    )
    op.alter_column(
        "forgetpasswordtoken",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("forgetpasswordtoken", "updated_at")
    op.drop_column("forgetpasswordtoken", "deleted_at")
    op.create_index(
        op.f("ix_confirmemailtoken_id"), "confirmemailtoken", ["id"], unique=False
    )
    op.alter_column(
        "confirmemailtoken",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("confirmemailtoken", "updated_at")
    op.drop_column("confirmemailtoken", "deleted_at")
    op.alter_column(
        "companyinvite",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("companyinvite", "updated_at")
    op.drop_column("companyinvite", "deleted_at")
    op.drop_column("company", "updated_at")
    op.drop_column("company", "deleted_at")
    op.drop_column("company", "created_at")
    # ### end Alembic commands ###
