"""file uploads

Revision ID: 0015
Revises: 0014
Create Date: 2026-05-02 10:56:53.877434

"""

from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0015"
down_revision: Union[str, Sequence[str], None] = "0014"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("kpeventnametagbackground_event_id_key"),
        "kpeventnametagbackground",
        type_="unique",
    )
    op.add_column(
        "storedfile",
        sa.Column(
            "sha256", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
    )
    op.drop_constraint(op.f("storedfile_storage_key_key"), "storedfile", type_="unique")
    op.create_index(
        op.f("ix_storedfile_sha256"), "storedfile", ["sha256"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_storedfile_sha256"), table_name="storedfile")
    op.create_unique_constraint(
        op.f("storedfile_storage_key_key"),
        "storedfile",
        ["storage_key"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("storedfile", "sha256")
    op.create_unique_constraint(
        op.f("kpeventnametagbackground_event_id_key"),
        "kpeventnametagbackground",
        ["event_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
