"""rename reset password token

Revision ID: 0019
Revises: 0018
Create Date: 2026-06-06 21:18:06.779051

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0019'
down_revision: Union[str, Sequence[str], None] = '0018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resetpasswordtoken',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resetpasswordtoken_expires_at'), 'resetpasswordtoken', ['expires_at'], unique=False)
    op.create_index(op.f('ix_resetpasswordtoken_token'), 'resetpasswordtoken', ['token'], unique=True)
    op.create_index(op.f('ix_resetpasswordtoken_user_id'), 'resetpasswordtoken', ['user_id'], unique=False)
    op.drop_index(op.f('ix_forgetpasswordtoken_expires_at'), table_name='forgetpasswordtoken')
    op.drop_index(op.f('ix_forgetpasswordtoken_token'), table_name='forgetpasswordtoken')
    op.drop_index(op.f('ix_forgetpasswordtoken_user_id'), table_name='forgetpasswordtoken')
    op.drop_table('forgetpasswordtoken')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forgetpasswordtoken',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_revoked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('forgetpasswordtoken_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('forgetpasswordtoken_pkey'))
    )
    op.create_index(op.f('ix_forgetpasswordtoken_user_id'), 'forgetpasswordtoken', ['user_id'], unique=False)
    op.create_index(op.f('ix_forgetpasswordtoken_token'), 'forgetpasswordtoken', ['token'], unique=True)
    op.create_index(op.f('ix_forgetpasswordtoken_expires_at'), 'forgetpasswordtoken', ['expires_at'], unique=False)
    op.drop_index(op.f('ix_resetpasswordtoken_user_id'), table_name='resetpasswordtoken')
    op.drop_index(op.f('ix_resetpasswordtoken_token'), table_name='resetpasswordtoken')
    op.drop_index(op.f('ix_resetpasswordtoken_expires_at'), table_name='resetpasswordtoken')
    op.drop_table('resetpasswordtoken')
    # ### end Alembic commands ###
