"""kp booklet fields, assets, and export tasks

Revision ID: 0024
Revises: 0023
Create Date: 2026-06-15 15:12:54.792803

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0024'
down_revision: Union[str, Sequence[str], None] = '0023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpeventbookletassets',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('intro_page_stored_file_id', sa.Uuid(), nullable=True),
    sa.Column('blank_page_stored_file_id', sa.Uuid(), nullable=True),
    sa.Column('missing_advertisement_stored_file_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['blank_page_stored_file_id'], ['storedfile.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['kpevent.id'], ),
    sa.ForeignKeyConstraint(['intro_page_stored_file_id'], ['storedfile.id'], ),
    sa.ForeignKeyConstraint(['missing_advertisement_stored_file_id'], ['storedfile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blank_page_stored_file_id'),
    sa.UniqueConstraint('event_id'),
    sa.UniqueConstraint('intro_page_stored_file_id'),
    sa.UniqueConstraint('missing_advertisement_stored_file_id')
    )
    op.create_table('kpeventbookletexporttask',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='kpeventbookletexporttaskstatus'), nullable=False),
    sa.Column('output_stored_file_id', sa.Uuid(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['kpevent.id'], ),
    sa.ForeignKeyConstraint(['output_stored_file_id'], ['storedfile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('output_stored_file_id')
    )
    op.create_index(op.f('ix_kpeventbookletexporttask_event_id'), 'kpeventbookletexporttask', ['event_id'], unique=False)
    op.create_index(op.f('ix_kpeventbookletexporttask_status'), 'kpeventbookletexporttask', ['status'], unique=False)
    op.add_column(
        'kpbookingcompanydetails',
        sa.Column(
            'website',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default=sa.text("''"),
        ),
    )
    op.add_column('kpbookingcompanydetails', sa.Column('vacancies_worldwide', sa.Integer(), nullable=True))
    op.add_column('kpbookingcompanydetails', sa.Column('vacancies_switzerland', sa.Integer(), nullable=True))
    op.add_column('kpbookingcompanydetails', sa.Column('annual_revenue_chf_millions', sa.Integer(), nullable=True))
    op.add_column('kpbookingcompanydetails', sa.Column('logo_stored_file_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint('uq_kpbookingcompanydetails_logo_stored_file_id', 'kpbookingcompanydetails', ['logo_stored_file_id'])
    op.create_foreign_key('fk_kpbookingcompanydetails_logo_stored_file_id_storedfile', 'kpbookingcompanydetails', 'storedfile', ['logo_stored_file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_kpbookingcompanydetails_logo_stored_file_id_storedfile', 'kpbookingcompanydetails', type_='foreignkey')
    op.drop_constraint('uq_kpbookingcompanydetails_logo_stored_file_id', 'kpbookingcompanydetails', type_='unique')
    op.drop_column('kpbookingcompanydetails', 'logo_stored_file_id')
    op.drop_column('kpbookingcompanydetails', 'annual_revenue_chf_millions')
    op.drop_column('kpbookingcompanydetails', 'vacancies_switzerland')
    op.drop_column('kpbookingcompanydetails', 'vacancies_worldwide')
    op.drop_column('kpbookingcompanydetails', 'website')
    op.drop_index(op.f('ix_kpeventbookletexporttask_status'), table_name='kpeventbookletexporttask')
    op.drop_index(op.f('ix_kpeventbookletexporttask_event_id'), table_name='kpeventbookletexporttask')
    op.drop_table('kpeventbookletexporttask')
    op.drop_table('kpeventbookletassets')
    # ### end Alembic commands ###
