"""kp event

Revision ID: 86bfe65cf38f
Revises: 048f38b20b08
Create Date: 2026-03-11 00:25:05.108340

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86bfe65cf38f'
down_revision: Union[str, Sequence[str], None] = '048f38b20b08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpevent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('registration_open', sa.Date(), nullable=False),
    sa.Column('registration_end', sa.Date(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpevent_year'), 'kpevent', ['year'], unique=True)
    op.create_table('kpeventcompanylink',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['kpevent.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'company_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kpeventcompanylink')
    op.drop_index(op.f('ix_kpevent_year'), table_name='kpevent')
    op.drop_table('kpevent')
    # ### end Alembic commands ###
