"""initial

Revision ID: 968392e3299b
Revises: cbc410340e7a
Create Date: 2026-02-16 21:27:19.226196

"""

from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "968392e3299b"
down_revision: Union[str, Sequence[str], None] = "cbc410340e7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "user_confirmed", sa.Boolean(), nullable=False, server_default="false"
        ),
    )
    # Map is_confirmed data to user_confirmed
    op.execute('UPDATE "user" SET user_confirmed = is_confirmed')
    op.drop_column("user", "is_confirmed")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "is_confirmed",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            server_default="false",
        ),
    )
    # Map user_confirmed data back to is_confirmed
    op.execute('UPDATE "user" SET is_confirmed = user_confirmed')
    op.drop_column("user", "user_confirmed")
    # ### end Alembic commands ###
