"""initial

Revision ID: cbc410340e7a
Revises: 5c93c2e06d65
Create Date: 2026-02-15 03:14:40.283430

"""

from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cbc410340e7a"
down_revision: Union[str, Sequence[str], None] = "5c93c2e06d65"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_role_name"), "role", ["name"], unique=True)
    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sub", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("email_confirmed", sa.Boolean(), nullable=False),
        sa.Column("is_staff", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_company", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_sub"), "user", ["sub"], unique=False)
    op.create_table(
        "confirmemailtoken",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_confirmemailtoken_id"), "confirmemailtoken", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_confirmemailtoken_token"), "confirmemailtoken", ["token"], unique=True
    )
    op.create_index(
        op.f("ix_confirmemailtoken_user_id"),
        "confirmemailtoken",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "forgetpasswordtoken",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_forgetpasswordtoken_id"), "forgetpasswordtoken", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_forgetpasswordtoken_token"),
        "forgetpasswordtoken",
        ["token"],
        unique=True,
    )
    op.create_index(
        op.f("ix_forgetpasswordtoken_user_id"),
        "forgetpasswordtoken",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "refreshtoken",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_refreshtoken_id"), "refreshtoken", ["id"], unique=False)
    op.create_index(
        op.f("ix_refreshtoken_token"), "refreshtoken", ["token"], unique=True
    )
    op.create_index(
        op.f("ix_refreshtoken_user_id"), "refreshtoken", ["user_id"], unique=False
    )
    op.create_table(
        "userrole",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("userrole")
    op.drop_index(op.f("ix_refreshtoken_user_id"), table_name="refreshtoken")
    op.drop_index(op.f("ix_refreshtoken_token"), table_name="refreshtoken")
    op.drop_index(op.f("ix_refreshtoken_id"), table_name="refreshtoken")
    op.drop_table("refreshtoken")
    op.drop_index(
        op.f("ix_forgetpasswordtoken_user_id"), table_name="forgetpasswordtoken"
    )
    op.drop_index(
        op.f("ix_forgetpasswordtoken_token"), table_name="forgetpasswordtoken"
    )
    op.drop_index(op.f("ix_forgetpasswordtoken_id"), table_name="forgetpasswordtoken")
    op.drop_table("forgetpasswordtoken")
    op.drop_index(op.f("ix_confirmemailtoken_user_id"), table_name="confirmemailtoken")
    op.drop_index(op.f("ix_confirmemailtoken_token"), table_name="confirmemailtoken")
    op.drop_index(op.f("ix_confirmemailtoken_id"), table_name="confirmemailtoken")
    op.drop_table("confirmemailtoken")
    op.drop_index(op.f("ix_user_sub"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_role_name"), table_name="role")
    op.drop_table("role")
    # ### end Alembic commands ###
